export const ideas = [
   `Power Down Make sure that everyone who is away from a computer for more than two hours shuts down completely. The surge of energy needed to power up is still way less energy than keeping the computer running for long periods of time.`,
   `Commit to a Reusable Coffee Cup - Saving five cups and lids over the course of a week amounts to nearly 300 during the year. Multiply that times the number of people who work just in your office, and it quickly adds up. Give everyone in the office a company-branded mug on Earth Day to reinforce the message`,
   `Add More Recycling Bins - Studies show sizable increases in recycling participation with more bins that are easily accessible. Send a note to co-workers to make sure they know where the bins are located.`,
   `Host a Drive to Collect E-waste - It’s estimated that only 12.5 percent of e-waste (tech hardware like old computers) is being recycled today, and that e-waste represents more than 70 percent of the toxic waste in landfills. Get your entire office park or building involved for good measure.`,
   `Use a Recyclable Water Bottle - The U.S. alone consumes more than 50 billion plastic water bottles annually. Get rid of plastic cups around the office water cooler. Hand out company-branded water bottles if you want to help the cause even more.`,
   `Plan a Telecommute Day - Go outside the office norm and do a work-from-home day in honor of Earth Day. You’ll save lots of energy in the process.`,
   `Arrange an Office-wide Carpool Day - You can start with a single day devoted to Earth Day, which could in turn encourage employees to try it more often.`,
   `Use Less Paper - Adopt a double-sided printing policy for all office correspondence.`,
   `Try to Be Paper Free for the Day - Ask employees to go a day (or even a week) without printing anything out. (Make exceptions for anything truly necessary but try to limit it.) This will hopefully give workers pause before they hit the “print” button next time.`,
   `Raise Money for a Local Environmental Group - Pick a worthy group in the community that empowers earth-friendly practices such as a nature conservancy or environmental action organization. The company can match employee donations.`,
   `Transform Trash to Treasure - Have young children bring in a variety of recyclable items such as milk cartons, toilet paper and paper towel rolls, egg cartons and more. Challenge their creativity to come up with new inventions and art projects with the materials.`,
   `Spend Extra Time Outdoors - Connecting with nature is vital to becoming motivated to protect it. Plan a week full of activities (weather permitting) that invite children to understand more about their local environment.`,
   `Plant a School Garden - A sense of ownership makes a big difference. Invite parents to help build any necessary beds and donate seeds and starter materials. Make it a fundraiser by having kids sell their products at the end of the season and donate the money to a worthy green cause.`,
   `Design Helpful Reminders - Have students create colorful signs for school and home such as, “Don’t forget to turn off the lights” or “Power down the computer when you’re done.”`,
   `Make a Homemade Bird Feeder - Use recycled items such as milk cartons, toilet paper rolls or empty water bottles and make a bird feeder that both reuses materials and helps creatures of the earth.`,
   `Collect Rainwater - Teach students about water conservation using a variety of methods from simple science experiments to larger-scale projects such as installing a rain barrel collection system or rain garden at your school.`,
   `Build a Micro-composter - Introduce students to nature’s way of recycling by building a micro-composter made up of 2-liter soda bottles. They can see the decomposition process up close and personal. (You can find detailed instructions online.)`,
   `Get Informed on Environmental Policies - A social studies or government class or club can do an exercise where students research local and federal policies related to the environment. Students can make suggestions to improve policies, decide which they would vote for, and host a brainstorming session to come up with ideas they would legislate if they were in office.`,
   `Understand Your Local Environmental Issues - Does your community face a water pollution problem, soil erosion or a faltering tree canopy? Help your community stay informed by putting together a listening session at a community center — or even writing an op-ed for a local publication.`,
   `Plan Educational Presentations - Take the above idea a little further by planning an evening or afternoon of presentations or a local “green action” day where community members can sign up for volunteer opportunities related to environmental causes. Contact local community centers, churches or libraries for possible venues.`,
   `Organize a Community Hike with a Nature Expert - Find a local who’s passionate about the unique environmental features of your area and whose enthusiasm encourages activism and time spent enjoying nature.`,
   `Participate in an Adopt-a-Highway Event - These programs not only work to clean up local environments but also to educate the public on the importance of proper trash disposal.`,
   `Join a Green Committee - Initiate or join a group dedicated to taking action on environmental issues important to your area.`,
   `Plant Trees in Community Areas - One acre of forest absorbs six tons of carbon dioxide and puts out four tons of oxygen, enough to meet the annual needs of 18 people, according the U.S. Department of Agriculture. Assess any areas in your neighborhood that could use a helping green thumb.`,
   `Join the “walking school bus” movement: recruit neighbor parents and take turns walking the kids to school.`,
   `Have a vegetarian day - Meat production significantly contributes to the release of greenhouse gases including carbon dioxide, methane and nitrous oxide. As large volumes of these greenhouse gases accumulate in the earth's atmosphere, they absorb radiation and prevent heat escaping. This leads to global warming. Try a salad to reduce your footprint.`,
   `Turn off lights in the home when they are not being used. This alone can cut energy costs greatly.`,
   `Don’t turn on lights at all for as long as you can. Open your curtains and use natural light.`,
   `Repurpose glass jars as leftover containers and bulk storage, especially in the kitchen.`,
   `Install sink water aerators. These are cheap and easy to install, and they greatly reduce the flow of water out of your sink, saving you money and water use.`,
   `Check if you can sign up for green power from your utility company. Also, conduct a quick energy audit of your home and replace electrical appliances with energy-efficient appliances`,
   `Unplug all of your electronics when they are not being used. Unplug unused chargers and appliances.`,
   `Use rechargeable batteries. Over time, invest in a full set of rechargeable batteries for all of your gadgets, remotes and smoke detectors in the house. Recharging batteries keeps dead ones out of the landfill and saves you money in the long run. Buy them on sale and stock up over time.`,
   ` Put a stop to unsolicited mail—sign up to opt out of pre-screened credit card offers.  While you’re at it, if you’re in the U.S., go ahead and make sure you’re on the “do not call” list, just to make life better.`,
   `Pay your bills online. Not only is it greener, it’s a sanity saver.`,
   `Use rags instead of disposable wipes.`,
   `Do a cold wash instead of a hot one. It still washes your clothes and can use up to 57% less electricity per wash. – Ariel`,
   `Drive at the speed limit. Boring? Yes. But it’s also safer, cheaper and better for the environment.`,
   `“Studies have shown up to 30% of the difference in miles per gallon (MPG) is due to driving habits alone. You could save more than a ton of CO2 per year by:
   – Accelerating slowly and smoothly
   – Driving the speed limit
   – Maintaining a steady speed
   – Anticipating your stops and starts” – Matter Of Trust`,
   `Drink Tap Water. Tap water is perfectly safe to drink in many parts of the world. Stop buying all those water bottles!`,
   `Read good natural living blogs on topics like sustainable living, zero waste home. See DIYs to reuse and reduce. Watch documentaries about the food industry and the environment.`,
   `Get e-tickets for the movies instead of buying paper tickets. Even file your taxes electronically to cut back on paper usage.`,
   `When in office, turn off all the peripherals such as printers, speakers and scanners when not in use.`,
   `Keep your tires inflated. Tires that are low pressure are going to cause more wear on the car and more harm to the environment.`,
   `Make your own cleaning solutions as store-bought cleaners are mostly full of chemicals that, in turn, pollute your home. There are tons of great cleaning formulas you can make at home that work just as well and cost few pennies to make. Just get some DIY cleaner recipes.`,
   `Support local restaurants that use food derived less than 100 miles away.`,
   `If possible, create a homemade compost bin and compost your food scraps. Composting can be done even if you live in an apartment and can save a ton of waste from going to the landfill. If you buy, the newer ones don’t even smell, and worm bins are even more efficient.`,
   `Buying products in bulk reduces the amount of packaging needed, thus providing considerable benefits to the environment.`,
   `Use recycled products whenever you can. This includes printer ink, paper, cardboard, etc. Even a reusable mug is good to have when you want to go green.`,
   `When washing clothing, make sure that you use cold water or warm water. Preferably wash laundry in cold water instead of hot. Using hot will take the machine longer to fill while consuming more water and using more energy.`,
   `Lower the temperature on your hot water heater.`,
   `Donate to—and shop at—thrift stores.  You’ll be recycling perfectly usable items, you’ll be supporting your local economy, and you’ll be saving money.`,
]